### ISSUE TITLE
절대경로 관련

### ISSUE THREAD

**Issue by J1min** [Bamdoliro/Stupetition-client-V1#24]
### ❓ Question

[여기](https://github.com/Bamdoliro/Stupetition-client-V1/blob/develop/src/components/layout/home/Main/PetitionList/index.tsx#L6)처럼 매우 복잡한 경로는 절대경로를 써도 좋을 것 같아요 

절대경로 참고
https://if1live.github.io/posts/use-absolute-path-in-typescript/

**Comment by SEOKKAMONI** [comment]
조언 감사합니다 ! 바로 적용하러가보겠습니당
