### ISSUE TITLE
버튼 컴포넌트 props 관련

### ISSUE THREAD

**Issue by J1min** [Bamdoliro/Stupetition-client-V1#25]
### ❓ Question

[여기](https://github.com/Bamdoliro/Stupetition-client-V1/blob/develop/src/types/common/button.type.ts#L3)처럼 커스텀 버튼을 만들어서 사용하는 경우는 interface를 아래처럼 extends하면 기존의 버튼태그에 있는 props들이 다 표시되어서 편할 것 같아요.
한번 고려해보시면 좋을 것 같습니다 !

```jsx
interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  type?: "submit" | "button";
  onClick?: MouseEventHandler<HTMLButtonElement>;
  children?: ReactNode;
  className?: string;
  varient?: ButtonVarient;
}
```

참고 : https://hackids.tistory.com/133

**Comment by SEOKKAMONI** [comment]
오.. 저런게 있었다니 .. 대단하네요.. 바로 적용하러가겠습니다

**Comment by SEOKKAMONI** [comment]
더해주세요..

**Comment by SEOKKAMONI** [comment]
적용했슴다

**Comment by J1min** [comment]
석진씨 디코있나요?? 실시간으로 ㄱㄱ?

**Comment by SEOKKAMONI** [comment]
오 게ㅐ좋아요

**Comment by SEOKKAMONI** [comment]
김석진#9335 입니당
