### ISSUE TITLE
className 삼항연산자 관련

### ISSUE THREAD

**Issue by J1min** [Bamdoliro/Stupetition-client-V1#30]
### ❓ Question

https://github.com/Bamdoliro/Stupetition-client-V1/blob/develop/src/components/common/Header/ProfilePopover/index.tsx#L8

위의 라인의 스타일 props는 아래와 같이 하는게 가독성과 불필요한 템플릿 리터럴을 없애서 더 좋을 것 같습니다
```jsx
<S.ProfilePopover style={isOpen ? { display: "none" } : null}>
```
그리고 위의 방법보다도 애초에 styled-components props를 받도록 하는게 베스트인것 같습니다 한번 고려해주세요

&&를 사용하지 않고 삼항연산자, null을 사용한 이유 : https://stackoverflow.com/questions/50377147/react-conditional-classnames-using-template-strings-and-operator

**Comment by SEOKKAMONI** [comment]
햇습니다 감사합니다
